// Language.js
const language = [
  { value: "Java", label: "Java" },
  { value: "Frontend_Angular", label: "Frontend Angular" },
  { value: ".net", label: "Dotnet" },
  { value: "Cyber security", label: "Cyber Security" },
  { value: "Devops", label: "DevOps" },
  { value: "Cloud Engineer", label: "Cloud Engineer" },
  { value: "Python", label: "Python" },
  { value: "Mainframe", label: "Mainframe" },
  { value: "IOT", label: "IOT" },
  { value: "Data Science", label: "Data Science" },
  { value: "PHP Developer", label: "PHP Developer" },
  { value: "RPA Developer", label: "RPA Developer" },
  { value: "QA", label: "QA" },
  { value: "Network Backup Admin", label: "Network Backup Admin" },
  { value: "C#", label: "C#" },
  { value: "Storage Admin", label: "Storage Admin" },
  { value: "Frontend_React", label: "Frontend React" },
  { value: "Node js", label: "Node js" },
  { value: "MS D365", label: "MS D365" },
  { value: "Network Engineer", label: "Network Engineer" },
  { value: "Docker", label: "Docker" },
  { value: "Digital Transformation", label: "Digital Transformation" },
  { value: "Product Owner", label: "Product Owner" },
  { value: "Project manager", label: "Project manager" },
  { value: "SQL", label: "SQL" },
  { value: "SFDC", label: "SFDC" },
  { value: "Sitecore Dev", label: "Sitecore Dev" },
  { value: "Sharepoint Developer", label: "Sharepoint Developer" },
  { value: "Servicenow Dev", label: "Servicenow Dev" },
  { value: "AI", label: "AI" },
  { value: "ML", label: "ML" },
  { value: "Flutter", label: "Flutter" },
  { value: "C++ Developer", label: "C++ Developer" },
];

export default language;
